server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1703a?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update